# Generated by Django 5.2.7 on 2025-10-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_fecha_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='fecha_publicacion',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='descripcion',
            new_name='detalle',
        ),
        migrations.AddField(
            model_name='noticia',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
