# Generated by Django 5.2.7 on 2025-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_rename_fecha_publicacion_noticia_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
