# Generated by Django 5.2.7 on 2025-10-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Comunidad',
        ),
    ]
