# Generated by Django 5.2.7 on 2025-10-31 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_rename_noticia_comunidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidad',
            options={'verbose_name': 'Comunidad', 'verbose_name_plural': 'Comunidad'},
        ),
    ]
